<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "catalog"
 *
 * Auto generated by Extension Builder 2017-02-04
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Eset catalog',
	'description' => 'Catalog of products',
	'category' => 'plugin',
	'author' => 'Roman Leitner',
	'author_email' => 'rleitner77@gmai.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-8.5.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);